name: Build, test and format check a Node.js console app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integrate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install linter dependencies
        run: npm ci
      - name: Check format
        run: npm run lint-check
      - name: Run tests
        run: npm run test
